const CATALOG = [
    {
        "id": "el1",
        "type": "Electronic",
        "name": "FENDER SQUIER BULLET STRAT HT HSS BLK",
        "img": "./src/img/catalog-guitars/img1.png",
        "price": 13600,
    },
    {
        "id": "el2",
        "type": "Bass",
        "name": "FENDER SQUIER AFFINITY",
        "img": "./src/img/catalog-guitars/img2.png",
        "price": 23900,
    },
    {
        "id": "el3",
        "type": "Bass",
        "name": "IBANEZ GIO GRG121DX-BKF BLACK FLAT",
        "img": "./src/img/catalog-guitars/img3.png",
        "price": 21600,
    },
    {
        "id": "el4",
        "type": "Electronic",
        "name": "EPIPHONE LES PAUL STUDIO LT EBONY",
        "img": "./src/img/catalog-guitars/img4.png",
        "price": 19900,
    },
    {
        "id": "el5",
        "type": "Electronic",
        "name": "FENDER SQUIER BULLET TREM HSS AWT",
        "img": "./src/img/catalog-guitars/img5.png",
        "price": 14500,
    },
    {
        "id": "el6",
        "type": "Acoustic",
        "name": "FENDER SK2000",
        "img": "./src/img/catalog-guitars/img6.png",
        "price": 14600,
    },
    {
        "id": "el7",
        "type": "Acoustic",
        "name": "FENDER SQUIER BULLET STRAT HT AWT",
        "img": "./src/img/catalog-guitars/img7.png",
        "price": 13600,
    },
    {
        "id": "el8",
        "type": "Bass",
        "name": "JACKSON JS22-7 DINKY SATIN BLACK",
        "img": "./src/img/catalog-guitars/img8.png",
        "price": 28700,
    },
    {
        "id": "el9",
        "type": "Bass",
        "name": "JACKSON JS11 DINKY OLYMPIC WHITE",
        "img": "./src/img/catalog-guitars/img9.png",
        "price": 18100,
    },
    {
        "id": "el10",
        "type": "Bass",
        "name": "Martin PACIFICA 012 WH",
        "img": "./src/img/catalog-guitars/img10.png",
        "price": 15990,
    },
    {
        "id": "el11",
        "type": "Acoustic",
        "name": "Gibson PACIFICA 012 WH",
        "img": "./src/img/catalog-guitars/img11.png",
        "price": 8800,
    },
    {
        "id": "el12",
        "type": "Bass",
        "name": "YAMAHA PACIFICA 012 WH",
        "img": "./src/img/catalog-guitars/img12.png",
        "price": 13400,
    },
    {
        "id": "el13",
        "type": "Electronic",
        "name": "Schecter PACIFICA 012 WH",
        "img": "./src/img/catalog-guitars/img13.png",
        "price": 11900,
    },
    {
        "id": "el14",
        "type": "Electronic",
        "name": "Gibson PACIFICA 012 WH",
        "img": "./src/img/catalog-guitars/img14.png",
        "price": 12200,
    },
    {
        "id": "el15",
        "type": "Bass",
        "name": "YAMAHA PACIFICA 012 WH",
        "img": "./src/img/catalog-guitars/img15.png",
        "price": 10400,
    },
    {
        "id": "el16",
        "type": "Bass",
        "name": "YAMAHA PACIFICA 012 WH",
        "img": "./src/img/catalog-guitars/img16.png",
        "price": 9800,
    },
    {
        "id": "el17",
        "type": "Acoustic",
        "name": "YAMAHA PACIFICA 012 WH",
        "img": "./src/img/catalog-guitars/img17.png",
        "price": 7400,
    },
    {
        "id": "el18",
        "type": "Acoustic",
        "name": "Gibson PACIFICA 012 WH",
        "img": "./src/img/catalog-guitars/img18.png",
        "price": 7700,
    },
    {
        "id": "el19",
        "type": "Acoustic",
        "name": "Martin PACIFICA 012 WH",
        "img": "./src/img/catalog-guitars/img19.png",
        "price": 9500,
    },
    {
        "id": "el20",
        "type": "Folk",
        "name": "YAMAHA PACIFICA 012 WH",
        "img": "./src/img/catalog-guitars/img20.png",
        "price": 6400,
    },
    {
        "id": "el21",
        "type": "Electronic",
        "name": "YAMAHA PACIFICA 012 WH",
        "img": "./src/img/catalog-guitars/img21.png",
        "price": 11700,
    },
    {
        "id": "el22",
        "type": "Bass",
        "name": "YAMAHA PACIFICA 012 WH",
        "img": "./src/img/catalog-guitars/img22.png",
        "price": 16400,
    },
    {
        "id": "el23",
        "type": "Electronic",
        "name": "Schecter PACIFICA 012 WH",
        "img": "./src/img/catalog-guitars/img23.png",
        "price": 12300,
    }, 
    {
        "id": "el24",
        "type": "Folk",
        "name": "Music Man PACIFICA 012 WH",
        "img": "./src/img/catalog-guitars/img24.png",
        "price": 5500,
    },
    {
        "id": "el25",
        "type": "Acoustic",
        "name": "Gibson PACIFICA 012 WH",
        "img": "./src/img/catalog-guitars/img29.png",
        "price": 7950,
    },
    {
        "id": "el26",
        "type": "Acoustic",
        "name": "Martin PACIFICA 012 WH",
        "img": "./src/img/catalog-guitars/img26.png",
        "price": 8500,
    },
    {
        "id": "el27",
        "type": "Folk",
        "name": "Music Man PACIFICA 012 WH",
        "img": "./src/img/catalog-guitars/img27.png",
        "price": 6000,
    },
    {
        "id": "el28",
        "type": "Folk",
        "name": "Music Man PACIFICA 012 WH",
        "img": "./src/img/catalog-guitars/img28.png",
        "price": 5900,
    },
]